### ISSUE TITLE
Ne lance plus de musique

### ISSUE THREAD

**Issue by adoublard** [QuentinCG/jarvis-music-player#6]
Depuis remise à zéro de ma rasp et jarvis pour pouvoir utiliser la sortie analogique, plus moyen de lancer une musique..

Jarvis: Salut DEBUG: stop_speaking hook User defined commands: *AIDE* *BONJOUR*|*SALUT* *COMMENT*APPELLE* *MERCI* *AU REVOIR*|*BYE* ANNULE*|TERMINE* ENCORE* *TEST* *VERSION* *REPETE (*) ET (*) *CA VA* >*OUI* >*NON*|*PAS* Commands from plugin jarvis-music-player: *MUSIQUE(*) *MUSIQUE* *STOP* *SUIVANT* *PRECEDENT* *ALEATOIRE* *MAJ* *DEMUTE* *MUTE* Alex: musique $> music="${BASH_REMATCH[1]}" && jv_pg_mp_go_to_specific_music "$music" && (jv_pg_mp_play_music && say "Fait.") || say "$music pas trouver." Server error: Could not start playback DEBUG: start_speaking hook Jarvis: Fait. DEBUG: stop_speaking hook Alex: 

Une idée pour résoudre ce problème ? :'(

**Comment by adoublard** [comment]
j'ai essayer de lancer xmms2 à la main avec -v pour obtenir les logs suivants : 



--- Starting new xmms2d ---
 INFO: ../src/xmms/log.c:49: Initialized logging system :)
 INFO: ../src/xmms/config.c:774: No configfile specified, using default values.
11:24:16  INFO: ../src/xmms/ipc.c:817: IPC listening on 'unix:///tmp/xmms-ipc-pi'.
11:24:16  FAIL: xmms_mediainfo_reader_wakeup: assertion 'mr' failed
11:24:16  INFO: ../src/xmms/main.c:550: Using output plugin: alsa
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM false
11:24:16 ERROR: ../src/plugins/alsa/alsa.c:220: Couldn't open device: default
11:24:16 ERROR: ../src/xmms/output.c:963: Could not initialize output plugin
11:24:16  INFO: ../src/xmms/xform.c:1364: Successfully setup chain for 'file:///usr/share/xmms2/silence-cellule_snippet.ogg' (1) containing file:magic:vorbis:segment
11:24:16  INFO: ../src/xmms/main.c:361: Installing scripts from /usr/share/xmms2/scripts/startup.d
11:24:16 ERROR: ../src/xmms/main.c:364: Global script directory not found
Failed in file ../src/lib/xmmstypes/value.c on  row 206
11:25:43  INFO: ../src/xmms/compat/signal_unix.c:61: Bye!
11:25:43  INFO: ../src/xmms/main.c:361: Installing scripts from /usr/share/xmms2/scripts/shutdown.d
11:25:43 ERROR: ../src/xmms/main.c:364: Global script directory not found
11:25:44  INFO: ../src/xmms/log.c:55: Logging says bye bye :)

**Comment by adoublard** [comment]
Ok, j'ai trouvé une solution, pour ceux qui auraient le soucis : 
faire la commande
ps -fux 
trouver xmms2, le kill, relancer jarvis et enjoy, le plugin fonctionne :)

**Comment by QuentinCG** [comment]
sinon, tu peux aussi utiliser la commande `pkill xmms2` ou encore relancer la raspberry pi pour résoudre ce genre de problème ;)
